name: Lint, Test, Deploy on push
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint step
        run: |
          echo "Start Lint step"
          npm init @eslint/config
          npm run lint
  
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Test step
        run: |
          echo "Start test"
          npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Build step
        run: |
          echo "Start build"
          npm run build